### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [AlexHolhosHOP/CustomCookieTag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) User instructions to install the template should direct users to install the gallery version of the template by clicking on the "Search Gallery" button in the template tab to add the gallery template.

**Comment by GrowthSavvy** [comment]
Hello!
I updated the user instructions and now I direct users to install the version found in the GTM Template Gallery.
Thank you!
